# WhatsApp Business API credentials
WHATSAPP_TOKEN = ""
WHATSAPP_PHONE_NUMBER_ID = ""
VERIFY_TOKEN = ""
VERSION = "v22.0"

# OpenAI API key
OPENAI_API_KEY = ""


# LangSmith configuration
LANGSMITH_TRACING = ""
LANGCHAIN_ENDPOINT = ""
LANGCHAIN_API_KEY = ""
LANGCHAIN_PROJECT = ""
